// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1:string,arg2:string):Promise<void>;

export function DownloadVideo(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetDB():Promise<string>;

export function StopSync():Promise<void>;

export function SyncPlaylist(arg1:string):Promise<void>;
