// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEntry(arg1, arg2) {
  return window['go']['main']['App']['AddEntry'](arg1, arg2);
}

export function DownloadVideo(arg1, arg2) {
  return window['go']['main']['App']['DownloadVideo'](arg1, arg2);
}

export function GetDB() {
  return window['go']['main']['App']['GetDB']();
}

export function SyncPlaylist(arg1) {
  return window['go']['main']['App']['SyncPlaylist'](arg1);
}
